// Bestemmingen = landen + regio's. `volume` is het gemeten maandelijkse zoekvolume (OpenSEO,
// oktober 2026, US/en, som van "esim X" + "best esim for X") en wordt enkel voor de volgorde
// op de homepage gebruikt, nooit getoond.
export const DESTINATIONS = [
  { slug: "united-states", name: "United States", type: "country", volume: 14000 },
  { slug: "japan", name: "Japan", type: "country", volume: 10800 },
  { slug: "europe", name: "Europe", type: "region", volume: 7200 },
  { slug: "united-kingdom", name: "United Kingdom", type: "country", volume: 2880 },
  { slug: "italy", name: "Italy", type: "country", volume: 2600 },
  { slug: "china", name: "China", type: "country", volume: 2000 },
  { slug: "canada", name: "Canada", type: "country", volume: 1920 },
  { slug: "mexico", name: "Mexico", type: "country", volume: 1780 },
  { slug: "france", name: "France", type: "country", volume: 1690 },
  { slug: "thailand", name: "Thailand", type: "country", volume: 1440 },
  { slug: "spain", name: "Spain", type: "country", volume: 1440 },
  { slug: "philippines", name: "Philippines", type: "country", volume: 1270 },
  { slug: "india", name: "India", type: "country", volume: 1270 },
  { slug: "australia", name: "Australia", type: "country", volume: 1260 },
  { slug: "vietnam", name: "Vietnam", type: "country", volume: 1200 },
  { slug: "turkey", name: "Turkey", type: "country", volume: 1140 },
  { slug: "costa-rica", name: "Costa Rica", type: "country", volume: 980 },
  { slug: "asia", name: "Asia", type: "region", volume: 870 },
  { slug: "portugal", name: "Portugal", type: "country", volume: 710 },
  { slug: "ireland", name: "Ireland", type: "country", volume: 710 },
  { slug: "south-korea", name: "South Korea", type: "country", volume: 640 },
  { slug: "germany", name: "Germany", type: "country", volume: 600 },
  { slug: "greece", name: "Greece", type: "country", volume: 580 },
  { slug: "indonesia", name: "Indonesia", type: "country", volume: 370 },
  { slug: "singapore", name: "Singapore", type: "country", volume: 370 },
  { slug: "global", name: "Worldwide", type: "region", volume: 380 },
  // Uitbreiding okt 2026 (OpenSEO US/en zoekvolume). Een land verschijnt alleen als >= 2 providers
  // geverifieerde prijzen hebben; de rest staat op noindex (zie lib/data.js, sitemap.js).
  { slug: "taiwan", name: "Taiwan", type: "country", volume: 1390 },
  { slug: "new-zealand", name: "New Zealand", type: "country", volume: 650 },
  { slug: "iceland", name: "Iceland", type: "country", volume: 530 },
  { slug: "colombia", name: "Colombia", type: "country", volume: 470 },
  { slug: "brazil", name: "Brazil", type: "country", volume: 460 },
  { slug: "peru", name: "Peru", type: "country", volume: 450 },
  { slug: "hong-kong", name: "Hong Kong", type: "country", volume: 380 },
  { slug: "switzerland", name: "Switzerland", type: "country", volume: 370 },
  { slug: "morocco", name: "Morocco", type: "country", volume: 370 },
  { slug: "dominican-republic", name: "Dominican Republic", type: "country", volume: 350 },
  { slug: "egypt", name: "Egypt", type: "country", volume: 320 },
  { slug: "south-africa", name: "South Africa", type: "country", volume: 230 },
  { slug: "israel", name: "Israel", type: "country", volume: 200 },
  { slug: "uae", name: "United Arab Emirates", type: "country", volume: 200 },
  { slug: "jamaica", name: "Jamaica", type: "country", volume: 180 },
  { slug: "panama", name: "Panama", type: "country", volume: 180 },
  { slug: "norway", name: "Norway", type: "country", volume: 180 },
  { slug: "sweden", name: "Sweden", type: "country", volume: 150 },
  { slug: "saudi-arabia", name: "Saudi Arabia", type: "country", volume: 150 },
  { slug: "croatia", name: "Croatia", type: "country", volume: 140 },
  { slug: "chile", name: "Chile", type: "country", volume: 140 },
  { slug: "ecuador", name: "Ecuador", type: "country", volume: 140 },
  { slug: "cuba", name: "Cuba", type: "country", volume: 120 },
  { slug: "albania", name: "Albania", type: "country", volume: 110 },
  { slug: "kenya", name: "Kenya", type: "country", volume: 110 },
  { slug: "pakistan", name: "Pakistan", type: "country", volume: 110 },
  { slug: "malaysia", name: "Malaysia", type: "country", volume: 100 },
  { slug: "denmark", name: "Denmark", type: "country", volume: 100 },
  { slug: "cambodia", name: "Cambodia", type: "country", volume: 100 },
  { slug: "lebanon", name: "Lebanon", type: "country", volume: 90 },
  { slug: "tanzania", name: "Tanzania", type: "country", volume: 80 },
  { slug: "jordan", name: "Jordan", type: "country", volume: 80 },
  { slug: "austria", name: "Austria", type: "country", volume: 80 },
  { slug: "tunisia", name: "Tunisia", type: "country", volume: 50 },
  { slug: "bahamas", name: "Bahamas", type: "country", volume: 30 },
  { slug: "laos", name: "Laos", type: "country", volume: 30 },
  { slug: "sri-lanka", name: "Sri Lanka", type: "country", volume: 30 },
  { slug: "romania", name: "Romania", type: "country", volume: 30 },
  { slug: "fiji", name: "Fiji", type: "country", volume: 30 },
  { slug: "hungary", name: "Hungary", type: "country", volume: 30 },
  { slug: "russia", name: "Russia", type: "country", volume: 30 },
  { slug: "puerto-rico", name: "Puerto Rico", type: "country", volume: 20 },
  { slug: "uzbekistan", name: "Uzbekistan", type: "country", volume: 20 },
  { slug: "argentina", name: "Argentina", type: "country", volume: 20 },
  { slug: "georgia", name: "Georgia", type: "country", volume: 20 },
  { slug: "maldives", name: "Maldives", type: "country", volume: 20 },
  { slug: "bolivia", name: "Bolivia", type: "country", volume: 10 },
  { slug: "cyprus", name: "Cyprus", type: "country", volume: 10 },
  { slug: "poland", name: "Poland", type: "country", volume: 10 },
  { slug: "qatar", name: "Qatar", type: "country", volume: 10 },
  { slug: "netherlands", name: "Netherlands", type: "country", volume: 10 },
];

export const DESTINATION_SLUGS = DESTINATIONS.map((d) => d.slug);

export function getDestination(slug) {
  return DESTINATIONS.find((d) => d.slug === slug) || null;
}

// Naam in lopende zin: "eSIM for Japan", "eSIM for the United States".
export function forName(d) {
  if (d.slug === "global") return "worldwide use";
  return d.name === "United States" || d.name === "United Kingdom" ? `the ${d.name}` : d.name;
}
